export const defaultJobs = [
    {
        "employer_name": "E-Solutions",
        "employer_logo": "https://media.glassdoor.com/sqll/425440/e-solutions-squarelogo-1537548633301.png",
        "employer_website": "http://www.e-solutionsinc.com",
        "job_publisher": "LinkedIn",
        "job_id": "w8XEyFU13yAAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "Python Developer",
        "job_apply_link": "https://www.linkedin.com/jobs/view/python-developer-at-e-solutions-3500559373",
        "job_description": "Hello,\n\nHope you doing well,\n\nJob Title: Python Developer\n\nLocation: Austin, TX\n\nFull Time\n\nJD:\n\nPython role requirements -\n\n1. Development capability – Python backend API/Service to read the data from either from file or database as the source, then do ETL\n\n2. Independent, who can coordinate with business understand the requirements, do extraction, translation/transform and load to the target\n\nUnfeigned Regards,\n\nShiv Prakash | Technical Recruiter\n\nDesk: (669)-309-1745\n\nEmail: Shiv.p@e-solutionsinc.com\n\n2N Market St, Suite # 400, San Jose, CA- 95113\n\nWebsite: www.e-solutionsinc.com\n\nUSA | CANADA | UK | SINGAPORE | MALAYSIA | INDIA\n\nDisclaimer: E-Solutions provides equal employment opportunities (EEO) to all employees and applicants for employment without regard to race, color, religion, gender, sexual orientation, gender identity or expression, national origin, age, disability, genetic information, marital status, amnesty, or status as a covered veteran in accordance with applicable federal, state and local laws. We especially invite women, minorities, veterans, and individuals with disabilities to apply. EEO/AA/M/F/Vet/Disability",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1677620749,
        "job_posted_at_datetime_utc": "2023-02-28T21:45:49.000Z",
        "job_city": "Austin",
        "job_state": "TX",
        "job_country": "US",
        "job_latitude": 30.267153,
        "job_longitude": -97.74306,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=w8XEyFU13yAAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-03-30T21:45:49.000Z",
        "job_offer_expiration_timestamp": 1680212749,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": false,
            "experience_preferred": false
        },
        "job_required_skills": null,
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": true,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {
            "Qualifications": [
                "Development capability – Python backend API/Service to read the data from either from file or database as the source, then do ETL"
            ]
        }
    },
    {
        "employer_name": "Wipro",
        "employer_logo": "https://www.wipro.com/content/dam/nexus/staticsites/cloud/assets/images/header/Wipro_Logo_Secondary_Color_Digital.svg",
        "employer_website": "http://www.wipro.com",
        "job_publisher": "LinkedIn",
        "job_id": "tVQiZfb7MewAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "Python Developer with SOAR",
        "job_apply_link": "https://www.linkedin.com/jobs/view/python-developer-with-soar-at-wipro-3500471654",
        "job_description": "Title - Python Developer with SOAR\n\nDuration - Permanent Full Time\n\nLocation - Westlake TX / Austin TX ( Initially Remote )\n\nJob Description:\n\n· Experience integrating and debugging multiple APIs and connections\n\n· Python development/scripting and testing experience\n\n· Ability to create, update, and maintain Playbooks and Workflows while minimizing impact for related services\n\n· Has a good understanding of end-to-end development from speaking with customers and gathering requirements to delivering the feature\n\n· Excellent verbal and written communication skills\n\n· Excellent analytical, documentation, and critical-thinking skills\n\n· Ability to prioritize tasks\n\n· Experience delivering automations with a SOAR platform to support the organizations security requirements\n\n· Ability to work in a team environment\n\n· Experience with Incident management\n\nNote:\n• Wipro is an Equal Employment Opportunity employer and makes all employment and employment-related decisions without regard to a person's race, sex, national origin, ancestry, disability, sexual orientation, or any other status protected by applicable law.",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1677605654,
        "job_posted_at_datetime_utc": "2023-02-28T17:34:14.000Z",
        "job_city": "Dallas",
        "job_state": "TX",
        "job_country": "US",
        "job_latitude": 32.776665,
        "job_longitude": -96.79699,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=tVQiZfb7MewAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-03-30T17:34:14.000Z",
        "job_offer_expiration_timestamp": 1680197654,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": true,
            "experience_preferred": false
        },
        "job_required_skills": null,
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": true,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {
            "Qualifications": [
                "Python development/scripting and testing experience",
                "Excellent verbal and written communication skills",
                "Excellent analytical, documentation, and critical-thinking skills",
                "Experience delivering automations with a SOAR platform to support the organizations security requirements",
                "Ability to work in a team environment",
                "Experience with Incident management"
            ],
            "Responsibilities": [
                "Experience integrating and debugging multiple APIs and connections",
                "Ability to create, update, and maintain Playbooks and Workflows while minimizing impact for related services"
            ]
        }
    },
    {
        "employer_name": "Centraprise",
        "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXnr3-A6Snj0QMpkBzuR1VZDv8edFAoqtRwruD&s=0",
        "employer_website": "http://www.centraprise.com",
        "job_publisher": "LinkedIn",
        "job_id": "Hqbat3BJRsUAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "Python Developer",
        "job_apply_link": "https://www.linkedin.com/jobs/view/python-developer-at-centraprise-3497547914",
        "job_description": "Hi,\n\nI am Shaikh Mujahed a US IT Recruiter - Resourcing with Centraprise. We are one of the top 50 fastest growing IT staffing and services firms in the nation specializing in staff augmentation in the areas of software applications, telecommunications and infrastructure. We are one of the largest minorities owned staffing firms in the U.S. I viewed your resume on one of the job boards; I understand that you may be actively looking for new opportunities.\n\nJob Title: Senior Python Developer\n\nLocation: Austin, TX\n\nJob Type: Fulltime/ Permanent\n\nJob Description:\n\n· Should be strong in Python programming\n\n· Experience in working with various interfaces (like communicating the robot with external devices and application code to run the automated testing)\n\n· Machine Learning experience is preferred\n\n· Experience in Data Movement, Data Transformation\n\n· Good knowledge on Cloud platform\n\nThanks & Regards\n\nShaikh Mujahed\n\nDesk: 732-481-1974",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1677620568,
        "job_posted_at_datetime_utc": "2023-02-28T21:42:48.000Z",
        "job_city": "Austin",
        "job_state": "TX",
        "job_country": "US",
        "job_latitude": 30.267153,
        "job_longitude": -97.74306,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=Hqbat3BJRsUAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-03-30T21:42:48.000Z",
        "job_offer_expiration_timestamp": 1680212568,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": true,
            "experience_preferred": true
        },
        "job_required_skills": [
            "Python (Programming Language)",
            "Data Science",
            "Learning",
            "Artificial Intelligence (AI)",
            "Pattern Recognition",
            "Machine Learning",
            "Job Boards",
            "Data Mining",
            "Programming",
            "Interfaces"
        ],
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": true,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {
            "Qualifications": [
                "Should be strong in Python programming",
                "Experience in working with various interfaces (like communicating the robot with external devices and application code to run the automated testing)",
                "Experience in Data Movement, Data Transformation",
                "Good knowledge on Cloud platform"
            ]
        }
    },
    {
        "employer_name": "Infosys",
        "employer_logo": "https://cdn-ukwest.onetrust.com/logos/8d84415b-1b52-4bc4-8d5f-ca9a8eccaf8a/f7db8968-fc22-4620-92ac-dc05c5d2aa15/02460a41-565e-4cac-80a7-449bc8f77a72/logo-infosys.png",
        "employer_website": "http://www.infosys.com",
        "job_publisher": "LinkedIn",
        "job_id": "C-68FLFSOK8AAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "Python Developer",
        "job_apply_link": "https://www.linkedin.com/jobs/view/python-developer-at-infosys-3500057423",
        "job_description": "Job Description:\n\nInfosys is seeking a Senior Python Developer - This position’s primary responsibility will be to design, development and implement solution to automate reference data integration with Power ETRM system. The chosen candidate will assist in the technical design of large business systems; builds applications, interface between applications, understand data security, retention, and recovery. The role holder should be able to research on technologies independently to recommend appropriate solutions & should contribute to technology-specific best practices & standards; contribute to success criteria from design through deployment, including, reliability, cost-effectiveness, performance, data integrity, maintainability, and scalability; contributes expertise on significant application components, program languages, databases, operating systems, etc., and guides/mentors the team during the build and test phases.\n\nBasic Qualifications\n\n• Bachelor’s degree or foreign equivalent required from an accredited institution. Will also consider three years of progressive experience in the specialty in lieu of every year of education.\n\n• At least 5 years' experience in Information Technology\n\n• Experience in developing applications in Python language\n\nRequired Qualifications\n\n• 5+ Years of experience in developing applications in Python language\n\n• Enterprise software development experience, namely building and supporting enterprise line of business applications in mixed-platform environments (.NET/Oracle/SQL Server)\n\n• Proficient in dimensional database design and data modelling\n\n• Expertise in loading huge volume of data, performance tuning and database partitioning.\n\n• 4+ years’ experience in Data Analysis and Data Migration\n\n• Performance tuning of complex SQL queries in Oracle / MS SQL Server / PostgreSQL.\n\n• Involve in identifying gaps and providing solutions based on client queries by collaborating with various cross functional teams.\n\n• Act as a liaison between the client and the technical teams for development & reports related queries.\n\n• Work on building a data strategy solution as per client needs by researching best industry practices.\n\n• Have experience in delivering project with Agile and Scrum methodology\n\n• Knowledge on ETRM / Oil and gas domain\n\n• Should have good analytical & reasoning abilities.",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1677517697,
        "job_posted_at_datetime_utc": "2023-02-27T17:08:17.000Z",
        "job_city": "Houston",
        "job_state": "TX",
        "job_country": "US",
        "job_latitude": 29.760427,
        "job_longitude": -95.369804,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=C-68FLFSOK8AAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-03-29T17:08:16.000Z",
        "job_offer_expiration_timestamp": 1680109696,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": 36,
            "experience_mentioned": true,
            "experience_preferred": false
        },
        "job_required_skills": null,
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": true,
            "degree_mentioned": true,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {
            "Qualifications": [
                "The role holder should be able to research on technologies independently to recommend appropriate solutions & should contribute to technology-specific best practices & standards; contribute to success criteria from design through deployment, including, reliability, cost-effectiveness, performance, data integrity, maintainability, and scalability; contributes expertise on significant application components, program languages, databases, operating systems, etc., and guides/mentors the team during the build and test phases",
                "Bachelor’s degree or foreign equivalent required from an accredited institution",
                "Will also consider three years of progressive experience in the specialty in lieu of every year of education",
                "At least 5 years' experience in Information Technology",
                "5+ Years of experience in developing applications in Python language",
                "Enterprise software development experience, namely building and supporting enterprise line of business applications in mixed-platform environments (.NET/Oracle/SQL Server)",
                "Proficient in dimensional database design and data modelling",
                "Expertise in loading huge volume of data, performance tuning and database partitioning",
                "4+ years’ experience in Data Analysis and Data Migration",
                "Performance tuning of complex SQL queries in Oracle / MS SQL Server / PostgreSQL",
                "Involve in identifying gaps and providing solutions based on client queries by collaborating with various cross functional teams",
                "Act as a liaison between the client and the technical teams for development & reports related queries",
                "Work on building a data strategy solution as per client needs by researching best industry practices",
                "Have experience in delivering project with Agile and Scrum methodology",
                "Knowledge on ETRM / Oil and gas domain",
                "Should have good analytical & reasoning abilities"
            ],
            "Responsibilities": [
                "The chosen candidate will assist in the technical design of large business systems; builds applications, interface between applications, understand data security, retention, and recovery"
            ]
        }
    },
    {
        "employer_name": "Vitol",
        "employer_logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Vitol_logo.svg/1200px-Vitol_logo.svg.png",
        "employer_website": "http://www.vitol.com",
        "job_publisher": "Learn4Good.com",
        "job_id": "U_erDD4Vbh0AAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "Python Developer",
        "job_apply_link": "https://www.learn4good.com/jobs/houston/texas/software_development/2123782217/e/",
        "job_description": "Job Description\n\nThe Python Developer will have the following responsibilities:\n\n• Writing modular, reusable components to liaise between external sources of data, internal tools and databases\n\n• Maintaining the cleanliness and centrality of the Vitol Python codebase\n\n• Porting of legacy code into Python where appropriate\n\n• Able to translate business requirements into a technical delivery following existing patters where possible\n\n• Other duties as assigned. This job description is subject to change at any time\n\n• Attendance is an essential function to this role",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1677542400,
        "job_posted_at_datetime_utc": "2023-02-28T00:00:00.000Z",
        "job_city": "Houston",
        "job_state": "TX",
        "job_country": "US",
        "job_latitude": 29.760427,
        "job_longitude": -95.369804,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=U_erDD4Vbh0AAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-03-10T00:00:00.000Z",
        "job_offer_expiration_timestamp": 1678406400,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": false,
            "experience_preferred": false
        },
        "job_required_skills": null,
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {
            "Responsibilities": [
                "The Python Developer will have the following responsibilities:",
                "Writing modular, reusable components to liaise between external sources of data, internal tools and databases",
                "Maintaining the cleanliness and centrality of the Vitol Python codebase",
                "Porting of legacy code into Python where appropriate",
                "Able to translate business requirements into a technical delivery following existing patters where possible",
                "Other duties as assigned"
            ]
        }
    },
    {
        "employer_name": "Wipro",
        "employer_logo": "https://www.wipro.com/content/dam/nexus/staticsites/cloud/assets/images/header/Wipro_Logo_Secondary_Color_Digital.svg",
        "employer_website": "http://www.wipro.com",
        "job_publisher": "LinkedIn",
        "job_id": "AXws1hF6y6MAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "Python Developer",
        "job_apply_link": "https://www.linkedin.com/jobs/view/python-developer-at-wipro-3457750994",
        "job_description": "About Wipro\n\nWipro Limited (NYSE: WIT, BSE: 507685, NSE: WIPRO) is a leading technology services and consulting company focused on building innovative solutions that address clients’ most complex digital transformation needs.\n\nWe leverage our holistic portfolio of capabilities in consulting, design, engineering, operations, and emerging technologies to help clients realize their boldest ambitions and build future-ready, sustainable businesses.\n\nA company recognized globally for its comprehensive portfolio of services, strong commitment to sustainability and good corporate citizenship, we have over 250,000 dedicated employees serving clients across 66 countries.\n\nWe deliver on the promise of helping our customers, colleagues, and communities thrive in an ever-changing world.\n\n· A PROUD HISTORY OF OVER 75 YEARS\n\n· FY22 REVENUE 10.4 BN USD\n\n· WE’RE PRESENT IN 66 COUNTRIES\n\n· OVER 1,400 ACTIVE GLOBAL CLIENTS\n• *** We are hiring for Python Developer In Austin, TX and looking for who can join on-site immediately ****\n\nRole: Python App Developer\n\nLocation: Austin, TX\n\nJob Type: On-site\n\nExperience: 4+ years\n\nRole Description:\n• Must-have: Python Application Development, Python Web development frameworks - Django / Flask, APIs, Microservices, ORMs, Linux, Git, REST, DevOps\n• Good to Have: Hands-on experience with Python libraries – NumPy, Pandas, AWS, Docker, Familiarity with Frond End Technologies – JavaScript, HTML, CSS\n\nWipro is an Equal Employment Opportunity employer and makes all employment and employment-related decisions without regard to a person's race, sex, national origin, ancestry, disability, sexual orientation, or any other status protected by applicable law.",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1675179585,
        "job_posted_at_datetime_utc": "2023-01-31T15:39:45.000Z",
        "job_city": "Austin",
        "job_state": "TX",
        "job_country": "US",
        "job_latitude": 30.267153,
        "job_longitude": -97.74306,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=AXws1hF6y6MAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-03-02T15:39:44.000Z",
        "job_offer_expiration_timestamp": 1677771584,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": true,
            "experience_preferred": false
        },
        "job_required_skills": null,
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": true,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {
            "Qualifications": [
                "Experience: 4+ years",
                "Good to Have: Hands-on experience with Python libraries – NumPy, Pandas, AWS, Docker, Familiarity with Frond End Technologies – JavaScript, HTML, CSS"
            ]
        }
    },
    {
        "employer_name": "EPIC SYSTEMS INC",
        "employer_logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Epic.png/200px-Epic.png",
        "employer_website": "http://www.epic.com",
        "job_publisher": "Learn4Good.com",
        "job_id": "gkPfcu_rKdcAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "Python Developer",
        "job_apply_link": "https://www.learn4good.com/jobs/houston/texas/software_development/2123117658/e/",
        "job_description": "Hello,\n\nThis is Nirosha from Epic Systems.\n\nPosition:\n\nPython Developer\n\nLocation Houston,TX--Onsite from day 1\n\nExperience:\n\n8+\n\nResponsibilities:\n\nDesign and build horizontally salable components within the major platform that the team is developing.\n\nReview and provide code feedback in terms of best practices with keen eye towards performance and stability optimizations.\n\nRequirements:\n\nExpertise in functional and object-oriented programming, specifically in Python\n\nExperience in databases (relational/document/etc.) including No\n\nSQL databases.\n\nStrong in algorithms and data structures\n\nExperience building distributed and scalable complex services as well as robust micro services.\n\nExperience writing unit tests in Pytest or Unittest\n\nAbility to provide technical guidance to peer team members.\n\nExperience writing tests (unit, integration, etc.)\n\nWorking knowledge of CI/CD pipelines and automation\n\nDesired\n\nSkills:\n\nBachelor's degree in computer science, math or a technical discipline\n\nExperience with Python, AMPS, Web Socket's, Apache Spark\n\nExperience with Java, Scala, C, C++ is a plus\n\nExposure to Agile software development process",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1677542400,
        "job_posted_at_datetime_utc": "2023-02-28T00:00:00.000Z",
        "job_city": "Houston",
        "job_state": "TX",
        "job_country": "US",
        "job_latitude": 29.760427,
        "job_longitude": -95.369804,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=gkPfcu_rKdcAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-08-27T00:00:00.000Z",
        "job_offer_expiration_timestamp": 1693094400,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": true,
            "experience_preferred": true
        },
        "job_required_skills": null,
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": true,
            "degree_preferred": true,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {
            "Qualifications": [
                "Expertise in functional and object-oriented programming, specifically in Python",
                "Experience in databases (relational/document/etc.) including No",
                "SQL databases",
                "Strong in algorithms and data structures",
                "Experience building distributed and scalable complex services as well as robust micro services",
                "Experience writing unit tests in Pytest or Unittest",
                "Experience writing tests (unit, integration, etc.)",
                "Working knowledge of CI/CD pipelines and automation",
                "Bachelor's degree in computer science, math or a technical discipline",
                "Experience with Python, AMPS, Web Socket's, Apache Spark",
                "Exposure to Agile software development process"
            ],
            "Responsibilities": [
                "Design and build horizontally salable components within the major platform that the team is developing",
                "Review and provide code feedback in terms of best practices with keen eye towards performance and stability optimizations"
            ]
        }
    },
    {
        "employer_name": "SynergisticIT",
        "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-UrAK1LCetSvno8PT3nMB4vJV4VdEEPN7PrgC&s=0",
        "employer_website": null,
        "job_publisher": "LinkedIn",
        "job_id": "D-0omzqVMXYAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "Entry Level Python Developer",
        "job_apply_link": "https://www.linkedin.com/jobs/view/entry-level-python-developer-at-synergisticit-3415227705",
        "job_description": "About Us\n\nSynergistic IT is a full-service staffing and placement firm servicing client in America for the past 12+ years. We are dedicated towards fulfilling the IT needs of our clients. From staffing to full implementation of projects we provide the highest quality IT Services. We Intend to deliver exceptional student outcome. We don't just help you secure a tech job but build a solid career in technology.\n\nJob Description\n• Should know how to work in large verities of libraries, frameworks, and modules\n• Duck typing, string, tuple and Lambda knowledge required\n• Django Frame work required\n• Worked on Django model, CBV, Django CRUD operation\n\nSkills Required-\n• Knowledge of Python web frameworks and event-driven programming in Python.\n• Basic understanding of front-end technologies.\n• High attention to detail.\n• Excellent communication and problem-solving skills.\n• Proficient understanding of code versioning tools\n• Know the classes of SCALA, Traits of SCALA, and Collection of SCALA\n\nEducation Requirement: -\n\nBachelors, Masters in Computer Science/ Computer Engineering/ Information Systems/Information Technology/ Electrical Engineering/ Mechanical Engineering.\n\nBenefits\n• On Job Technical support\n• E- verified\n• Help to get H1B Employer.\n• Full time position\n\nCandidate who are missing the required skills, might be provided an option to enhance their skills, so that they can also apply for the role and can make a career in IT industry.\n\nIf you do respond via e-mail, please include a daytime phone number so that we can reach you. In considering candidates, time is of the essence, so please respond ASAP. Thank you",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1672614428,
        "job_posted_at_datetime_utc": "2023-01-01T23:07:08.000Z",
        "job_city": "Houston",
        "job_state": "TX",
        "job_country": "US",
        "job_latitude": 29.760427,
        "job_longitude": -95.369804,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=D-0omzqVMXYAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-03-03T05:07:15.000Z",
        "job_offer_expiration_timestamp": 1677820035,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": false,
            "experience_preferred": false
        },
        "job_required_skills": null,
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": true,
            "degree_mentioned": true,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {
            "Qualifications": [
                "Knowledge of Python web frameworks and event-driven programming in Python",
                "Basic understanding of front-end technologies",
                "High attention to detail",
                "Excellent communication and problem-solving skills",
                "Proficient understanding of code versioning tools",
                "Know the classes of SCALA, Traits of SCALA, and Collection of SCALA",
                "Bachelors, Masters in Computer Science/ Computer Engineering/ Information Systems/Information Technology/ Electrical Engineering/ Mechanical Engineering"
            ],
            "Responsibilities": [
                "Should know how to work in large verities of libraries, frameworks, and modules",
                "Django Frame work required",
                "Worked on Django model, CBV, Django CRUD operation"
            ],
            "Benefits": [
                "On Job Technical support",
                "Full time position"
            ]
        }
    },
    {
        "employer_name": "LeadStack Inc.",
        "employer_logo": "https://media.licdn.com/dms/image/C560BAQHH5l5vOUv-AA/company-logo_200_200/0/1650480254170?e=2147483647&v=beta&t=vL7FqNuIrO-doGv-ZS0o6L6oaoeiEgt0kRzHVdkGQe4",
        "employer_website": "http://www.leadstackinc.com",
        "job_publisher": "LinkedIn",
        "job_id": "aRLCmZ9YwXUAAAAAAAAAAA==",
        "job_employment_type": "CONTRACTOR",
        "job_title": "Python Software Engineering",
        "job_apply_link": "https://www.linkedin.com/jobs/view/python-software-engineering-at-leadstack-inc-3505540857",
        "job_description": "LeadStack Inc. is an award-winning, one of the nation’s fastest-growing, certified minority-owned (MBE) staffing services provider of contingent workforce. As a recognized industry leader in contingent workforce solutions and Certified as a Great Place to Work, we’re proud to partner with some of the most admired Fortune 500 brands in the world\n\nJob Title: Python Software Engineering\n\nLocation: Dallas, TX\n\nDuration: 6+ Months Contract\n\nJob Description:\n• This person will be responsible for integrating data sources into internal data services.\n• Example include pulling network configuration data and converting into OpenConfig format, working with partners to sync IPAMs / SoTs, and pushing metadata into ServiceNow.\n• Work will be accomplished using Python3 and a modified Apache Airflow.\n\nMinimum Qualifications:\n• 5 years of professional Python3 experience\n\nAdditional Optional Preferred Qualifications:\n• 3 years of experience working with ETL Tools, Apache Airflow preferred\n• Deep understanding of Antlr4\n• GoLang experience\n\nTo know more about current opportunities at LeadStack Inc., please visit us on https://leadstackinc.com/careers/\n\nShould you have any questions, feel free to call me on 4088838922 or send an email on ankit.sapkale@leadstackinc.com",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1677624098,
        "job_posted_at_datetime_utc": "2023-02-28T22:41:38.000Z",
        "job_city": "Dallas",
        "job_state": "TX",
        "job_country": "US",
        "job_latitude": 32.776665,
        "job_longitude": -96.79699,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=aRLCmZ9YwXUAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-03-30T22:41:38.000Z",
        "job_offer_expiration_timestamp": 1680216098,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": 60,
            "experience_mentioned": true,
            "experience_preferred": true
        },
        "job_required_skills": null,
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": true,
            "degree_mentioned": true,
            "degree_preferred": false,
            "professional_certification_mentioned": true
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": 70,
        "job_max_salary": 75,
        "job_salary_currency": "USD",
        "job_salary_period": "HOUR",
        "job_highlights": {
            "Qualifications": [
                "5 years of professional Python3 experience"
            ],
            "Responsibilities": [
                "This person will be responsible for integrating data sources into internal data services",
                "Example include pulling network configuration data and converting into OpenConfig format, working with partners to sync IPAMs / SoTs, and pushing metadata into ServiceNow",
                "Work will be accomplished using Python3 and a modified Apache Airflow"
            ]
        }
    },
    {
        "employer_name": "TAGCOR",
        "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8i49TxmypL921gwSrXCigLk762K1u2Qu9yW0x&s=0",
        "employer_website": null,
        "job_publisher": "Recruit.net",
        "job_id": "-SgnorS481MAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "Python Developer",
        "job_apply_link": "https://www.recruit.net/job/python-developer-jobs/B61A67FE6C5E5515",
        "job_description": "Python Developer\nTexas - Dallas\n8 Years\n- /- ( )\nRequired Skills\nPython Developer education qualification\n• UG :- - Not Required\n• PG :- - Not Required\n• Work with engineering and architecture to assess critical challenges and identify opportunities to define automated solutions for workflow optimization\n• Cultivate innovation by driving cross-collaboration and execution of projects across multiple teams\n• Own complex problems and have the ability to break it down into simpler components to lead the process of designing, developing, testing, deploying, maintaining and software improvement\n• Work with all customers of the network to define necessary network software controls, visibility, and requirements to sustain business growth\n• Mentor and train other team members on design techniques, and coding standards\n• Serve in a 24/7 on-call rotation as an escalation contact for service trouble incidents\nRequired Qualifications\n• BS in Computer Science or related professional experience In-depth knowledge of Linux/Unix operating systems.\n• 8+ years programming/software engineering experience in any combination of Perl, Python, Go, C/C++\n• Experience in developing software and monitoring large scale distributed systems\n• Experience with CI/CD deployment methodology and other common DevOps tools (i.e. Jenkins, Docker, Git) and orchestration frameworks such as Chef/Ansible a huge plus.\n• Experience with NoSQL/RDBMS, Message bus and similar big data technologies (Redis, ElasticSearch, Kafka)\n• Experience with NFV and containerization (Docker, Kubernetes) a big plus\n• Experience in manageability infrastructure tools including Ansible, Rest/gRPC, Rest/NetConf\n• Data analytics, modeling, pipelines, representation, UI and API experience\n• Working knowledge and experience of Agile software development methodologies. Leading and training modern software engineering practices and the full software development life cycle such as planning, designing, coding standards, testing (unit, functional), and code reviews.\n• Outstanding collaboration and communication, and documentation skills with a proven ability to work cross-functionally in order to establish and meet shared goals",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1677542400,
        "job_posted_at_datetime_utc": "2023-02-28T00:00:00.000Z",
        "job_city": "Dallas",
        "job_state": "TX",
        "job_country": "US",
        "job_latitude": 32.776665,
        "job_longitude": -96.79699,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=-SgnorS481MAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-03-30T00:00:00.000Z",
        "job_offer_expiration_timestamp": 1680134400,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": 96,
            "experience_mentioned": true,
            "experience_preferred": true
        },
        "job_required_skills": null,
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": true,
            "degree_preferred": true,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {
            "Qualifications": [
                "Python Developer education qualification",
                "UG :- - Not Required",
                "PG :- - Not Required",
                "BS in Computer Science or related professional experience In-depth knowledge of Linux/Unix operating systems",
                "8+ years programming/software engineering experience in any combination of Perl, Python, Go, C/C++",
                "Experience in developing software and monitoring large scale distributed systems",
                "Experience with CI/CD deployment methodology and other common DevOps tools (i.e",
                "Jenkins, Docker, Git) and orchestration frameworks such as Chef/Ansible a huge plus",
                "Experience with NoSQL/RDBMS, Message bus and similar big data technologies (Redis, ElasticSearch, Kafka)",
                "Experience with NFV and containerization (Docker, Kubernetes) a big plus",
                "Experience in manageability infrastructure tools including Ansible, Rest/gRPC, Rest/NetConf",
                "Data analytics, modeling, pipelines, representation, UI and API experience",
                "Working knowledge and experience of Agile software development methodologies",
                "Leading and training modern software engineering practices and the full software development life cycle such as planning, designing, coding standards, testing (unit, functional), and code reviews"
            ],
            "Responsibilities": [
                "Cultivate innovation by driving cross-collaboration and execution of projects across multiple teams",
                "Work with all customers of the network to define necessary network software controls, visibility, and requirements to sustain business growth",
                "Mentor and train other team members on design techniques, and coding standards",
                "Serve in a 24/7 on-call rotation as an escalation contact for service trouble incidents"
            ]
        }
    }
]

export const fieldsDefaultValues = {
    UN_DISCLOSED: "Undisclosed",
    WORLD_WIDE: "Worldwide",
}

export const countries = {
    "US": "United States",
    "CA": "Canada",
    "MX": "Mexico",
    "JP": "Japan",
    "CN": "China",
    "KR": "South Korea",
    "AU": "Australia",
    "GB": "United Kingdom",
    "DE": "Germany",
    "FR": "France",
    'DK': 'Denmark',
    'NO': 'Norway',
    'PL': 'Poland',
    'CH': 'Switzerland',
    'UA': 'Ukraine',
    'SE': 'Sweden',
    'EE': 'Estonia',
    'FI': 'Finland',
    'NL': 'Netherlands',
    "ES": "Spain",
    "IT": "Italy",
    "RU": "Russia",
    "BR": "Brazil",
    "AR": "Argentina",
    "IN": "India",
    "AZ": "Azerbaijan",
}